/*flexberryautogenerated="true"*/
namespace IIS.Atelier
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ОдеждаL : BaseListForm<Одежда>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ОдеждаL() : base(Одежда.Views.ОдеждаL)
        {
            EditPage = ОдеждаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Odezhda/OdezhdaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
