//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Atelier
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [BusinessServer("IIS.Atelier.ОтменаЗаказа, Atelier.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "Размеры as \'Размеры\'",
            "Стоимость as \'Стоимость\'",
            "Состояние as \'Состояние\'",
            "ДатаОформленияЗаказа as \'Дата оформления заказа\'",
            "ДатаОплаты as \'Дата оплаты\'",
            "ДатаВыдачиТовара as \'Дата выдачи товара\'",
            "Клиент as \'Клиент\'",
            "Клиент.Мастер.Фамилия",
            "Клиент.Мастер.Имя",
            "Клиент.Мастер.Отчество",
            "Клиент.Мастер.ФИО as \'Мастер\'",
            "Одежда as \'Одежда\'"}, Hidden=new string[] {
            "Клиент.Мастер.Фамилия",
            "Клиент.Мастер.Имя",
            "Клиент.Мастер.Отчество"})]
    [View("ЗаказL", new string[] {
            "Клиент.Фамилия",
            "Клиент.Имя",
            "Клиент.Отчество",
            "Клиент.ФИО as \'Клиент\'",
            "Клиент.Телефон as \'Телефон\'",
            "Клиент.Мастер.Фамилия",
            "Клиент.Мастер.Имя",
            "Клиент.Мастер.Отчество",
            "Клиент.Мастер.ФИО as \'Мастер\'",
            "Размеры as \'Размеры\'",
            "Стоимость as \'Стоимость\'",
            "Состояние as \'Состояние\'",
            "ДатаОформленияЗаказа as \'Дата оформления заказа\'",
            "ДатаОплаты as \'Дата оплаты\'",
            "ДатаВыдачиТовара as \'Дата выдачи товара\'",
            "Одежда.Материал as \'Материал\'",
            "Одежда.Фасон as \'Фасон\'",
            "Одежда.Покрой as \'Покрой\'",
            "Одежда.Стиль as \'Стиль\'",
            "Одежда.Вид as \'Вид\'"}, Hidden=new string[] {
            "Клиент.Фамилия",
            "Клиент.Имя",
            "Клиент.Отчество",
            "Клиент.Мастер.Фамилия",
            "Клиент.Мастер.Имя",
            "Клиент.Мастер.Отчество"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private string fРазмеры;
        
        private decimal fСтоимость;
        
        private IIS.Atelier.СостояниеЗаказа fСостояние;
        
        private System.DateTime fДатаОформленияЗаказа;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОплаты;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаВыдачиТовара;
        
        private IIS.Atelier.Клиент fКлиент;
        
        private IIS.Atelier.Одежда fОдежда;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Размеры.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Размеры CustomAttributes)

        // *** End programmer edit section *** (Заказ.Размеры CustomAttributes)
        [StrLen(255)]
        public virtual string Размеры
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Размеры Get start)

                // *** End programmer edit section *** (Заказ.Размеры Get start)
                string result = this.fРазмеры;
                // *** Start programmer edit section *** (Заказ.Размеры Get end)

                // *** End programmer edit section *** (Заказ.Размеры Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Размеры Set start)

                // *** End programmer edit section *** (Заказ.Размеры Set start)
                this.fРазмеры = value;
                // *** Start programmer edit section *** (Заказ.Размеры Set end)

                // *** End programmer edit section *** (Заказ.Размеры Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Заказ.Стоимость CustomAttributes)
        public virtual decimal Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Стоимость Get start)

                // *** End programmer edit section *** (Заказ.Стоимость Get start)
                decimal result = this.fСтоимость;
                // *** Start programmer edit section *** (Заказ.Стоимость Get end)

                // *** End programmer edit section *** (Заказ.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Стоимость Set start)

                // *** End programmer edit section *** (Заказ.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Заказ.Стоимость Set end)

                // *** End programmer edit section *** (Заказ.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Состояние CustomAttributes)

        // *** End programmer edit section *** (Заказ.Состояние CustomAttributes)
        public virtual IIS.Atelier.СостояниеЗаказа Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Состояние Get start)

                // *** End programmer edit section *** (Заказ.Состояние Get start)
                IIS.Atelier.СостояниеЗаказа result = this.fСостояние;
                // *** Start programmer edit section *** (Заказ.Состояние Get end)

                // *** End programmer edit section *** (Заказ.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Состояние Set start)

                // *** End programmer edit section *** (Заказ.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Заказ.Состояние Set end)

                // *** End programmer edit section *** (Заказ.Состояние Set end)
            }
        }
        
        /// <summary>
        /// ДатаОформленияЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОформленияЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОформленияЗаказа CustomAttributes)
        public virtual System.DateTime ДатаОформленияЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОформленияЗаказа Get start)

                // *** End programmer edit section *** (Заказ.ДатаОформленияЗаказа Get start)
                System.DateTime result = this.fДатаОформленияЗаказа;
                // *** Start programmer edit section *** (Заказ.ДатаОформленияЗаказа Get end)

                // *** End programmer edit section *** (Заказ.ДатаОформленияЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОформленияЗаказа Set start)

                // *** End programmer edit section *** (Заказ.ДатаОформленияЗаказа Set start)
                this.fДатаОформленияЗаказа = value;
                // *** Start programmer edit section *** (Заказ.ДатаОформленияЗаказа Set end)

                // *** End programmer edit section *** (Заказ.ДатаОформленияЗаказа Set end)
            }
        }
        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаВыдачиТовара.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаВыдачиТовара CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаВыдачиТовара CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаВыдачиТовара
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаВыдачиТовара Get start)

                // *** End programmer edit section *** (Заказ.ДатаВыдачиТовара Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаВыдачиТовара;
                // *** Start programmer edit section *** (Заказ.ДатаВыдачиТовара Get end)

                // *** End programmer edit section *** (Заказ.ДатаВыдачиТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаВыдачиТовара Set start)

                // *** End programmer edit section *** (Заказ.ДатаВыдачиТовара Set start)
                this.fДатаВыдачиТовара = value;
                // *** Start programmer edit section *** (Заказ.ДатаВыдачиТовара Set end)

                // *** End programmer edit section *** (Заказ.ДатаВыдачиТовара Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Atelier.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Клиент Get start)

                // *** End programmer edit section *** (Заказ.Клиент Get start)
                IIS.Atelier.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заказ.Клиент Get end)

                // *** End programmer edit section *** (Заказ.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Клиент Set start)

                // *** End programmer edit section *** (Заказ.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заказ.Клиент Set end)

                // *** End programmer edit section *** (Заказ.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Одежда CustomAttributes)

        // *** End programmer edit section *** (Заказ.Одежда CustomAttributes)
        [PropertyStorage(new string[] {
                "Одежда"})]
        [NotNull()]
        public virtual IIS.Atelier.Одежда Одежда
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Одежда Get start)

                // *** End programmer edit section *** (Заказ.Одежда Get start)
                IIS.Atelier.Одежда result = this.fОдежда;
                // *** Start programmer edit section *** (Заказ.Одежда Get end)

                // *** End programmer edit section *** (Заказ.Одежда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Одежда Set start)

                // *** End programmer edit section *** (Заказ.Одежда Set start)
                this.fОдежда = value;
                // *** Start programmer edit section *** (Заказ.Одежда Set end)

                // *** End programmer edit section *** (Заказ.Одежда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Atelier.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Atelier.Заказ));
                }
            }
        }
    }
}
