//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Atelier
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРождения as \'Дата рождения\'",
            "Телефон as \'Телефон\'",
            "Мастер",
            "Мастер.ФИО as \'ФИО\'"})]
    [View("КлиентL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРождения as \'Дата рождения\'",
            "Телефон as \'Телефон\'",
            "Мастер.ФИО as \'Мастер\'"})]
    public class Клиент : IIS.Atelier.Личность
    {
        
        private IIS.Atelier.Сотрудник fМастер;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Мастер CustomAttributes)

        // *** End programmer edit section *** (Клиент.Мастер CustomAttributes)
        [PropertyStorage(new string[] {
                "Мастер"})]
        [NotNull()]
        public virtual IIS.Atelier.Сотрудник Мастер
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Мастер Get start)

                // *** End programmer edit section *** (Клиент.Мастер Get start)
                IIS.Atelier.Сотрудник result = this.fМастер;
                // *** Start programmer edit section *** (Клиент.Мастер Get end)

                // *** End programmer edit section *** (Клиент.Мастер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Мастер Set start)

                // *** End programmer edit section *** (Клиент.Мастер Set start)
                this.fМастер = value;
                // *** Start programmer edit section *** (Клиент.Мастер Set end)

                // *** End programmer edit section *** (Клиент.Мастер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.Atelier.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.Atelier.Клиент));
                }
            }
        }
    }
}
