//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Atelier
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Одежда.
    /// </summary>
    // *** Start programmer edit section *** (Одежда CustomAttributes)

    // *** End programmer edit section *** (Одежда CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОдеждаE", new string[] {
            "Вид as \'Вид\'",
            "Материал as \'Материал\'",
            "Фасон as \'Фасон\'",
            "Покрой as \'Покрой\'",
            "Стиль as \'Стиль\'"})]
    [View("ОдеждаL", new string[] {
            "Вид as \'Вид\'",
            "Материал as \'Материал\'",
            "Фасон as \'Фасон\'",
            "Покрой as \'Покрой\'",
            "Стиль as \'Стиль\'"})]
    public class Одежда : ICSSoft.STORMNET.DataObject
    {
        
        private string fВид;
        
        private string fМатериал;
        
        private string fФасон;
        
        private string fПокрой;
        
        private string fСтиль;
        
        // *** Start programmer edit section *** (Одежда CustomMembers)

        // *** End programmer edit section *** (Одежда CustomMembers)

        
        /// <summary>
        /// Вид.
        /// </summary>
        // *** Start programmer edit section *** (Одежда.Вид CustomAttributes)

        // *** End programmer edit section *** (Одежда.Вид CustomAttributes)
        [StrLen(255)]
        public virtual string Вид
        {
            get
            {
                // *** Start programmer edit section *** (Одежда.Вид Get start)

                // *** End programmer edit section *** (Одежда.Вид Get start)
                string result = this.fВид;
                // *** Start programmer edit section *** (Одежда.Вид Get end)

                // *** End programmer edit section *** (Одежда.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Одежда.Вид Set start)

                // *** End programmer edit section *** (Одежда.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Одежда.Вид Set end)

                // *** End programmer edit section *** (Одежда.Вид Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (Одежда.Материал CustomAttributes)

        // *** End programmer edit section *** (Одежда.Материал CustomAttributes)
        [StrLen(255)]
        public virtual string Материал
        {
            get
            {
                // *** Start programmer edit section *** (Одежда.Материал Get start)

                // *** End programmer edit section *** (Одежда.Материал Get start)
                string result = this.fМатериал;
                // *** Start programmer edit section *** (Одежда.Материал Get end)

                // *** End programmer edit section *** (Одежда.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Одежда.Материал Set start)

                // *** End programmer edit section *** (Одежда.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (Одежда.Материал Set end)

                // *** End programmer edit section *** (Одежда.Материал Set end)
            }
        }
        
        /// <summary>
        /// Фасон.
        /// </summary>
        // *** Start programmer edit section *** (Одежда.Фасон CustomAttributes)

        // *** End programmer edit section *** (Одежда.Фасон CustomAttributes)
        [StrLen(255)]
        public virtual string Фасон
        {
            get
            {
                // *** Start programmer edit section *** (Одежда.Фасон Get start)

                // *** End programmer edit section *** (Одежда.Фасон Get start)
                string result = this.fФасон;
                // *** Start programmer edit section *** (Одежда.Фасон Get end)

                // *** End programmer edit section *** (Одежда.Фасон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Одежда.Фасон Set start)

                // *** End programmer edit section *** (Одежда.Фасон Set start)
                this.fФасон = value;
                // *** Start programmer edit section *** (Одежда.Фасон Set end)

                // *** End programmer edit section *** (Одежда.Фасон Set end)
            }
        }
        
        /// <summary>
        /// Покрой.
        /// </summary>
        // *** Start programmer edit section *** (Одежда.Покрой CustomAttributes)

        // *** End programmer edit section *** (Одежда.Покрой CustomAttributes)
        [StrLen(255)]
        public virtual string Покрой
        {
            get
            {
                // *** Start programmer edit section *** (Одежда.Покрой Get start)

                // *** End programmer edit section *** (Одежда.Покрой Get start)
                string result = this.fПокрой;
                // *** Start programmer edit section *** (Одежда.Покрой Get end)

                // *** End programmer edit section *** (Одежда.Покрой Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Одежда.Покрой Set start)

                // *** End programmer edit section *** (Одежда.Покрой Set start)
                this.fПокрой = value;
                // *** Start programmer edit section *** (Одежда.Покрой Set end)

                // *** End programmer edit section *** (Одежда.Покрой Set end)
            }
        }
        
        /// <summary>
        /// Стиль.
        /// </summary>
        // *** Start programmer edit section *** (Одежда.Стиль CustomAttributes)

        // *** End programmer edit section *** (Одежда.Стиль CustomAttributes)
        [StrLen(255)]
        public virtual string Стиль
        {
            get
            {
                // *** Start programmer edit section *** (Одежда.Стиль Get start)

                // *** End programmer edit section *** (Одежда.Стиль Get start)
                string result = this.fСтиль;
                // *** Start programmer edit section *** (Одежда.Стиль Get end)

                // *** End programmer edit section *** (Одежда.Стиль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Одежда.Стиль Set start)

                // *** End programmer edit section *** (Одежда.Стиль Set start)
                this.fСтиль = value;
                // *** Start programmer edit section *** (Одежда.Стиль Set end)

                // *** End programmer edit section *** (Одежда.Стиль Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОдеждаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОдеждаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОдеждаE", typeof(IIS.Atelier.Одежда));
                }
            }
            
            /// <summary>
            /// "ОдеждаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОдеждаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОдеждаL", typeof(IIS.Atelier.Одежда));
                }
            }
        }
    }
}
