//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Atelier
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Цех.
    /// </summary>
    // *** Start programmer edit section *** (Цех CustomAttributes)

    // *** End programmer edit section *** (Цех CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЦехE", new string[] {
            "Номер as \'Номер\'"})]
    [View("ЦехL", new string[] {
            "Номер as \'Номер\'"})]
    public class Цех : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        // *** Start programmer edit section *** (Цех CustomMembers)

        // *** End programmer edit section *** (Цех CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Цех.Номер CustomAttributes)

        // *** End programmer edit section *** (Цех.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Цех.Номер Get start)

                // *** End programmer edit section *** (Цех.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Цех.Номер Get end)

                // *** End programmer edit section *** (Цех.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Цех.Номер Set start)

                // *** End programmer edit section *** (Цех.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Цех.Номер Set end)

                // *** End programmer edit section *** (Цех.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЦехE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦехE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦехE", typeof(IIS.Atelier.Цех));
                }
            }
            
            /// <summary>
            /// "ЦехL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦехL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦехL", typeof(IIS.Atelier.Цех));
                }
            }
        }
    }
}
